version: '3.8'
services:
  postgres:
    container_name: projetocomputacao
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - POSTGRES_DB:projetoDB
    ports:
      - 5441:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
